#!/bin/bash
###############################################################################
#                                   _ _
#                                  | (_)
#  __ _ _   _  ___ _   _  ___    __| |_ ___  ___ _____   _____ _ __ _   _
# / _` | | | |/ _ \ | | |/ _ \  / _` | / __|/ __/ _ \ \ / / _ \ '__| | | |
#| (_| | |_| |  __/ |_| |  __/ | (_| | \__ \ (_| (_) \ V /  __/ |  | |_| |
# \__, |\__,_|\___|\__,_|\___|  \__,_|_|___/\___\___/ \_/ \___|_|   \__, |
#    | |                                                             __/ |
#    |_|                                                            |___/
#
# Lets discover all the queues and its types from the IBM MQ!
#
#
# by spectroman at yahoo.com ## 09-05-2017
#
#


if [[ $# -lt 1 ]]; then
    echo "Usage: $0 QUEUEMANAGERNAME"
    exit 1
fi

LOCAL=$(dirname $0)
CFG=$LOCAL/mq-config

. $CFG

declare -a QUEUES

QQUERY=`echo "DISPLAY QUEUE(*)" | $SUDOUSER $RUNMQSC_BIN $1`

RES=$?
if [[  "$RES" -gt 0 ]]; then
  echo "There was a problem executing the Queue Manager discovery, please check it manually"
  exit 1;
fi

IFS=$'\n'
CNT=0

for line in ${QQUERY[@]}; do
  if [[ ! $line =~ QUEUE\((AMQ.*)\) ]]; then
    if [[ $line =~ QUEUE\((.*)\)[[:space:]]*TYPE\((.*)\) ]]; then
      CNT=$(($CNT+1))
      QUEUES[$CNT]=${BASH_REMATCH[1]}"|"${BASH_REMATCH[2]}
    fi
  fi
done

IFS=''

NUMIT=${#QUEUES[@]}
PRN=0

for arritem in ${QUEUES[@]}; do
  IFS='|'
  declare -a subitm
  subitm=($arritem)
  nameq=${subitm[0]}
  typeq=${subitm[1]}

  if [[ "$NUMIT" == 1 ]] && [[ "$PRN" == 0 ]]; then
    echo "{" $arritem" }"
  else
    if [[ "$PRN" == 0 ]]; then
      echo "{ \"data\": ["
    fi
    if [[ $(($PRN + 1)) == "$NUMIT" ]]; then
      echo "{ \"{#QUEUE}\" : \" $nameq\","
      echo "  \"{#QTYPE}\" : \" $typeq\" }"
      echo "]}"
    elif [[ "$PRN" -lt "$NUMIT" ]]; then
      echo "{ \"{#QUEUE}\" : \" $nameq\","
      echo "  \"{#QTYPE}\" : \" $typeq\" },"
    fi
  fi
  PRN=$PRN+1
done
